[workspace]
members = [
    "macros",
    "define"
]


[package]
name = "auto-delegate"
version = "0.1.0"
edition = "2021"


[[test]]
name = "tests"
path = "tests/progress.rs"


[dependencies]
macros = { path = "macros" }
define = { path = "define" }
syn = { version = "2.0.15", features = ["full", "extra-traits", "derive"] }

[dev-dependencies]
trybuild = "1.0.80"