[workspace]
members = [
    "auto-delegate-macros",
]


[package]
name = "auto-delegate"
version = "0.1.0"
edition = "2021"



[[test]]
name = "tests"
path = "tests/progress.rs"


[dependencies]
syn = { version = "2.0.15", features = ["full", "extra-traits", "derive"] }
auto-delegate-macros = { path = "./auto-delegate-macros" }


[dev-dependencies]
trybuild = "1.0.80"

