[package]
name = "auto-delegate"
authors = ["elm-register <elmregister@gmail.com>"]
version = "0.0.4"
edition = "2021"
readme = "README.md"
repository = "https://github.com/elm-register/auto-delegate"
keywords = ["delegate", "trait", "macros"]
description = "Auto delegate allows you that automatic impl of traits and delegate their handling to child members."
license-file = "LICENSE"
categories = ["no-std"]


[workspace]
members = [
    "auto-delegate-macros"
]


[[bench]]
name = "cmp_handwritten_struct"
path = "benches/cmp_handwritten_struct.rs"
harness = false


[[bench]]
name = "cmp_handwritten_enum"
path = "benches/cmp_handwritten_enum.rs"
harness = false


[[test]]
name = "tests"
path = "tests/progress.rs"


[dependencies]
auto-delegate-macros = "0.0.4"


[dev-dependencies]
trybuild = "1.0.80"
criterion = { version = "0.4.0", features = ["html_reports"] }
async-trait = "0.1.68"
tokio = { version = "1.28.0", features = ["full"] }